// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
pipeline {
  parameters {
    string(name: 'sampleParam', description: 'Sample parameter ')
    string(name: 'node', defaultValue: 'Hadoop',
        description: 'the node label that should be used to run the test.')
  }
  agent {
    node {
      label "${params.node}"
    }
  }
  options {
    timeout (time: 6, unit: 'HOURS')
    timestamps()
  }
  environment {
    // where we check out to across stages
    BASEDIR = "${env.WORKSPACE}/component"
    OUTPUT_RELATIVE = 'output'
    OUTPUTDIR = "${env.WORKSPACE}/output"
  }
  stages {
    stage ('sample stage') {
      tools {
        maven 'Maven (latest)'
        // this needs to be set to the jdk that ought to be used to build releases on the branch
        // the Jenkinsfile is stored in.
        jdk "JDK 1.8 (latest)"
      }
      steps {
        sh """#!/bin/bash -e
          echo "Verifying hbck2"
"""
        }
      }
      post {
        always {
          archive 'output/*'
          archive 'output/**/*'
        }
        failure {
          archive 'component/**/target/surefire-reports/*'
        }
      }
    }
  }
}